version: "2"
linters:
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - staticcheck
        text: 'ST1001:'
        paths:
          - '.*design/.*\.go$'