#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}/example/weather

echo "Starting diagram editor..."

mdl serve goa.design/clue/example/weather/diagram -dir diagram -port 8085 front

popd
