#!/usr/bin/env bash

set -e

mkdir -p /tmp/cortex/rule
mkdir -p /tmp/tempo

echo "Starting services..."

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}/example/weather

source ./scripts/utils/common.sh

docker-compose -f docker-compose/docker-compose-grafana.yaml up -d 

overmind start

popd
