#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}/example/weather

source ./scripts/utils/common.sh

proto_pkg="protobuf-compiler"

# install protoc, update version as needed
PROTO_VER=25.1

if is_mac; then
  PROTOC_ZIP=protoc-${PROTO_VER}-osx-universal_binary.zip
  proto_pkg="protobuf"
else
  PROTOC_ZIP=protoc-${PROTO_VER}-linux-x86_64.zip
fi

curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTO_VER}/${PROTOC_ZIP}
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
rm -f $PROTOC_ZIP

check_required_cmd "protoc" $proto_pkg

if [[ "$CI" == "" ]]; then
  check_required_cmd "tmux"
fi

go mod download
go install goa.design/clue/mock/cmd/cmg@latest
go install goa.design/model/cmd/mdl@latest
go install goa.design/goa/v3/...@v3
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
go install github.com/DarthSim/overmind/v2@latest

# clone SigNoz for docker compose files
if [[ ! -d "signoz" ]]; then
  git clone --depth 1 -b main https://github.com/SigNoz/signoz.git
fi

./scripts/build

popd
