#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}/example/weather

source ./scripts/utils/common.sh

proto_pkg="protobuf-compiler"

if is_mac; then
  proto_pkg="protobuf"
fi

check_required_cmd "protoc" $proto_pkg

if [[ "$CI" == "" ]]; then
  check_required_cmd "tmux"
fi

go mod download
go install goa.design/clue/mock/cmd/cmg@latest
go install goa.design/model/cmd/mdl@latest
go install goa.design/goa/v3/...@v3
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
go install github.com/DarthSim/overmind/v2@latest

# clone SigNoz for docker compose files
if [[ ! -d "signoz" ]]; then
  git clone --depth 1 -b main https://github.com/SigNoz/signoz.git
  # remove the hotrod example
  sed -i.bak '/hotrod:/,$d' signoz/deploy/docker/clickhouse-setup/docker-compose.yaml
fi

./scripts/build

popd
