server:
  log_level: info
  http_listen_port: 12345
  graceful_shutdown_timeout: 10s

metrics:
  global:
    scrape_interval: 10s
  configs:
    - name: test
      host_filter: false
      scrape_configs:
        - job_name: front_scrape
          static_configs:
            - targets: ['host.docker.internal:8085']
        - job_name: locator_scrape
          static_configs:
            - targets: ['host.docker.internal:8083']
        - job_name: forecast_scrape
          static_configs:
            - targets: ['host.docker.internal:8081']
        - job_name: local_scrape
          static_configs:
            - targets: ['127.0.0.1:12345', '127.0.0.1:8889']
              labels:
                cluster: 'docker_compose'
                container: 'agent'
                pod: 'grafana-agent-local'
        - job_name: cortex_scrape
          static_configs:
            - targets: ['cortex:9009']
              labels:
                cluster: 'docker_compose'
                container: 'cortex'
      remote_write:
        - url: http://cortex:9009/api/prom/push

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
    - job_name: system
      static_configs:
        - targets:
          - localhost
          labels:
            job: varlogs
            __path__: /var/log/*log

traces:
  configs:
  - name: default
    receivers:
      otlp:
        protocols:
          grpc:
    remote_write:
      - endpoint: tempo:4317
        insecure: true
    batch:
      timeout: 5s
      send_batch_size: 100
    automatic_logging:
      backend: logs_instance
      logs_instance_name: default
      spans: true
      processes: true
      roots: true
    spanmetrics:
      handler_endpoint: 0.0.0.0:8889
    service_graphs:
      enabled: true
