// Code generated by Clue Mock Generator v0.18.2, DO NOT EDIT.
//
// Command:
// $ cmg gen goa.design/clue/example/weather/services/front/clients/locator

package mocklocator

import (
	"context"
	"testing"

	"goa.design/clue/mock"

	"goa.design/clue/example/weather/services/front/clients/locator"
)

type (
	Client struct {
		m *mock.Mock
		t *testing.T
	}

	ClientGetLocationFunc func(ctx context.Context, ip string) (*locator.WorldLocation, error)
)

func NewClient(t *testing.T) *Client {
	var (
		m                = &Client{mock.New(), t}
		_ locator.Client = m
	)
	return m
}

func (m *Client) AddGetLocation(f ClientGetLocationFunc) {
	m.m.Add("GetLocation", f)
}

func (m *Client) SetGetLocation(f ClientGetLocationFunc) {
	m.m.Set("GetLocation", f)
}

func (m *Client) GetLocation(ctx context.Context, ip string) (*locator.WorldLocation, error) {
	if f := m.m.Next("GetLocation"); f != nil {
		return f.(ClientGetLocationFunc)(ctx, ip)
	}
	m.t.Helper()
	m.t.Error("unexpected GetLocation call")
	return nil, nil
}

func (m *Client) HasMore() bool {
	return m.m.HasMore()
}
