#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
GOLANGCI_VER=1.53.3

pushd ${GIT_ROOT} > /dev/null

source ./scripts/utils/common.sh

if [[ "$CI" == "" ]]; then
  check_required_cmd "tmux"
fi

curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI_VER}

popd > /dev/null
