#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)

pushd ${GIT_ROOT} > /dev/null

source ./scripts/utils/common.sh

GOLANGCI_LINT_VERSION=${GOLANGCI_LINT_VERSION:-v2.12.1}

if [[ "$CI" == "" ]]; then
  check_required_cmd "tmux"
fi

go install "github.com/golangci/golangci-lint/v2/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}"

popd > /dev/null
