#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
# Ensure we are in the correct directory for the following commands
pushd ${GIT_ROOT} > /dev/null

echo "Running static analysis..."
golangci-lint run --timeout 5m --verbose

echo "Running tests..."
go test -race -coverprofile=coverage.out -covermode=atomic ./...

popd > /dev/null
