#!/usr/bin/env bash

set -e

echo "Running tests..."

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}

staticcheck ./...

go test -race -coverprofile=coverage.out -covermode=atomic ./...

popd
