#!/usr/bin/env bash

set -e

echo "Running tests..."

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}

staticcheck ./...

# Generate coverage reports for each sub-directory for badges
for d in $(go list ./...); do
    go test -coverprofile=$(basename $d).coverprofile -covermode=count ${d}
    go tool cover -func=$(basename $d).coverprofile -o=$(basename $d).coverprofile
done

popd
