openapi: 3.0.3
info:
  title: Goa API
  description: instrument test service
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for itest
paths:
  /{i}:
    post:
      tags:
      - test
      summary: http_method test
      operationId: test#http_method
      parameters:
      - name: i
        in: path
        description: Int operand
        required: true
        schema:
          type: integer
          description: Int operand
          example: 3649691564958456519
          format: int64
        example: 1375309373032297875
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HTTPMethodRequestBody'
            example:
              s: Voluptas exercitationem vitae.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fields'
              example:
                i: 4403340894134448357
                s: In modi et.
components:
  schemas:
    Fields:
      type: object
      properties:
        i:
          type: integer
          description: Int operand
          example: 6616172494300219579
          format: int64
        s:
          type: string
          description: String operand
          example: Recusandae quis est illum voluptatem.
      example:
        i: 2844263105501442990
        s: Aliquam facere officia.
    HTTPMethodRequestBody:
      type: object
      properties:
        s:
          type: string
          description: String operand
          example: Voluptatem dolor inventore possimus delectus minima ipsa.
      example:
        s: Quia laborum et distinctio dolores.
tags:
- name: test
